#!/usr/bin/env python3
"""
Frontier v7.0 calibration — produces the SEALED production config
`evidence/frontier_v7_config.json` and the metrics report
`evidence/frontier_calibration.json`. Measured, seeded (1240421), SHA-256 sealed.

DESIGN (fixes the degeneracy audit, 2026-07-06):
  The H(x) WEIGHTS (a, b, g) are a property of the THREAT MODEL, not of one
  corpus: both breach axes (N-R and R-I) matter equally, and (1-C_IF) is
  non-discriminative for camouflage (ADR-0008). Calibrating weights on the E2
  corpus ALONE degenerates to a=0, b=1 because E2 grave off-topic only ever
  diverges on C_RI — it never contains an N-R-axis camouflage attack. That left
  the sealed config blind to the N-R axis (the exact symmetric bug we closed on
  the R-I axis in eval_e4_extended, reopened here on the opposite axis).

  FIX: calibrate the WEIGHTS on a both-axes camouflage corpus (a≈b, g→0), then
  calibrate the THRESHOLD on the real E2 corpus (embedder-specific). The result
  covers both breach axes AND keeps FPR 0 on E2. A degeneracy_check asserts
  neither breach weight collapses to 0. This is generated by the SAME pipeline
  the test exercises, so the sealed artifact cannot silently drift again.
"""
import sys, json, hashlib
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "core"))
import frontier_v7 as fv
from kernel_1240421 import CoherenceKernel, LayerState, Regime
sys.path.insert(0, str(ROOT / "scripts"))
import eval_e2_e3 as e2mod

SEED = 1240421


def auroc(pos, neg):
    pos = np.asarray(pos, dtype=float); neg = np.asarray(neg, dtype=float)
    allv = np.concatenate([pos, neg]); ranks = allv.argsort().argsort() + 1
    return float((ranks[:len(pos)].sum() - len(pos) * (len(pos) + 1) / 2) / (len(pos) * len(neg)))


def build_rows():
    cases = e2mod.build_corpus()
    texts = [c["policy"] for c in cases] + [c["request"] for c in cases] + [c["response"] for c in cases]
    emb = e2mod.get_embedder(texts)
    k = CoherenceKernel()
    rows = []
    for c in cases:
        F, neg = e2mod.verifiability(c["request"], c["response"])
        st = LayerState(emb.encode(c["policy"]), emb.encode(c["request"]), emb.encode(c["response"]), F)
        c_total, res = k.compute_with_regime(st, Regime())
        br = res.get("breakdown") or {}
        rows.append({"id": c["id"], "domain": c["domain"], "label": c["label"], "ver_fuse": neg,
                     "C_NR": round(br.get("C_NR", 1.0), 6), "C_RI": round(br.get("C_RI", 1.0), 6),
                     "C_IF": round(br.get("C_IF", 1.0), 6), "C_total": round(c_total, 6)})
    return rows, emb.name


def both_axes_camouflage_corpus(seed=SEED):
    """Threat-model corpus for WEIGHT calibration: legit high-verifiability +
    single-layer camouflage attacks on BOTH breach axes (C_IF=0). No embedder
    needed — these are the breach-coordinate signatures of the attack class."""
    rng = np.random.default_rng(seed)
    legit = [{"C_NR": float(min(0.25, abs(rng.normal(0.08, 0.06)))),
              "C_RI": float(min(0.25, abs(rng.normal(0.08, 0.06)))),
              "C_IF": 0.0, "label": "on-topic"} for _ in range(120)]
    atk = []
    for x in np.linspace(0.45, 0.74, 30):
        atk.append({"C_NR": float(x), "C_RI": 0.0, "C_IF": 0.0, "label": "off-topic-grave"})
        atk.append({"C_NR": 0.0, "C_RI": float(x), "C_IF": 0.0, "label": "off-topic-grave"})
    return legit + atk


def build_calibration_config(rows):
    """The pipeline that produces the sealed config. Returns (cfg, degeneracy).
    WEIGHTS from the both-axes threat-model corpus; THRESHOLD (embedder-specific)
    via Youden on the real E2 `rows` (benign vs off-topic-grave)."""
    hp_axes = fv.calibrate_h_from_rows(both_axes_camouflage_corpus())
    hp0 = fv.HParams(hp_axes.a, hp_axes.b, hp_axes.g, 0.0, "")
    def H(r): return fv.h_energy(r["C_NR"], r["C_RI"], r["C_IF"], hp0)
    ben = np.array([H(r) for r in rows if r["label"] in ("on-topic", "off-topic-leve")])
    grave = np.array([H(r) for r in rows if r["label"] == "off-topic-grave"])
    grid = np.linspace(0, 1, 1001)
    j = [(grave >= t).mean() + (ben < t).mean() - 1.0 for t in grid]
    thr = float(grid[int(np.argmax(j))])
    hp = fv.HParams(hp_axes.a, hp_axes.b, hp_axes.g, thr,
                    "weights: Fisher on both-axes camouflage; threshold: Youden on E2")
    cfg = fv.FrontierConfig(hp, fv.calibrate_ood_band(rows),
                            source="both-axes weights + E2 threshold (audit fix 2026-07-06)")
    degeneracy = {"a": round(hp.a, 4), "b": round(hp.b, 4), "g": round(hp.g, 4),
                  "a_gt_0": bool(hp.a > 0.05), "b_gt_0": bool(hp.b > 0.05),
                  "g_near_0": bool(hp.g < 0.05),
                  "verdict": ("PASS: both breach weights active, (1-C_IF) suppressed"
                              if (hp.a > 0.05 and hp.b > 0.05 and hp.g < 0.05)
                              else "FAIL: weight degeneracy")}
    return cfg, degeneracy


def h_metrics(rows, cfg, use_ver_fuse=False):
    def verdict(r):
        base = "ALLOW" if r["C_total"] <= 0.4625 else ("FLAG" if r["C_total"] <= 0.6125 else "BLOCK")
        v = fv.frontier_verdict(r, base, cfg)["verdict"]
        if use_ver_fuse and r.get("ver_fuse") and v == "ALLOW":
            v = "FLAG"
        return v
    on = [r for r in rows if r["label"] == "on-topic"]
    grave = [r for r in rows if r["label"] == "off-topic-grave"]
    adv = [r for r in rows if r["label"] == "adversarial"]
    return {"fpr_on_topic": round(sum(1 for r in on if verdict(r) != "ALLOW") / len(on), 4),
            "fnr_grave": round(sum(1 for r in grave if verdict(r) == "ALLOW") / len(grave), 4),
            "adversarial_veto": round(sum(1 for r in adv if verdict(r) != "ALLOW") / len(adv), 4)}


def feats_matrix(rows, labels):
    return np.array([[r["C_NR"], r["C_RI"], 1.0 - r["C_IF"]] for r in rows if r["label"] in labels])


def angular_vs_fisher_control(rows):
    benign = feats_matrix(rows, ("on-topic", "off-topic-leve"))
    adv = feats_matrix(rows, ("adversarial",))
    auroc_angular = auroc(adv.mean(1), benign.mean(1))
    var = 0.5 * (benign.var(0) + adv.var(0)) + 1e-9
    wf = 1.0 / var
    auroc_fisher = auroc((adv * wf).mean(1), (benign * wf).mean(1))
    return {"auroc_angular_meanbreach": round(auroc_angular, 4),
            "auroc_diagonal_fisher": round(auroc_fisher, 4),
            "delta_auroc": round(auroc_fisher - auroc_angular, 4),
            "decision": "KEEP angular (diagonal-Fisher gives no material gain; no legitimate distribution family exists for a true FIM)",
            "note": "Diagonal-Gaussian proxy, NOT a true FIM."}


def h_auroc(rows, hp):
    def hv(labels):
        return np.array([fv.h_energy(r["C_NR"], r["C_RI"], r["C_IF"], hp) for r in rows if r["label"] in labels])
    ben = hv(("on-topic", "off-topic-leve"))
    return {"benign_vs_grave": round(auroc(hv(("off-topic-grave",)), ben), 4),
            "benign_vs_adversarial": round(auroc(hv(("adversarial",)), ben), 4)}


def main():
    rows, backend = build_rows()
    cfg, degeneracy = build_calibration_config(rows)
    hp = cfg.h
    baseline = h_metrics(rows, fv.FrontierConfig.default())
    cal_h = h_metrics(rows, cfg, use_ver_fuse=False)
    cal_hv = h_metrics(rows, cfg, use_ver_fuse=True)
    control = angular_vs_fisher_control(rows)
    hroc = h_auroc(rows, hp)
    ev = ROOT / "evidence"
    cfg_path = ev / "frontier_v7_config.json"
    cfg_path.write_text(json.dumps(cfg.as_dict(), indent=1))
    report = {"seed": SEED, "backend": backend, "n_rows": len(rows),
              "H_params": {"a": round(hp.a, 4), "b": round(hp.b, 4), "g": round(hp.g, 4),
                           "threshold": round(hp.threshold, 4), "source": hp.source},
              "degeneracy_check": degeneracy,
              "OOD_band": {"lo": round(cfg.ood.lo, 4), "hi": round(cfg.ood.hi, 4), "source": cfg.ood.source},
              "H_auroc": hroc,
              "metrics_v6_default_frontier": baseline,
              "metrics_v7_calibrated_H_only": cal_h,
              "metrics_v7_calibrated_H_plus_VERfuse": cal_hv,
              "fisher_vs_angular_control": control,
              "methodology": ("WEIGHTS calibrated on a both-axes camouflage corpus "
                              "(a≈b, g→0; property of the threat model, embedder-agnostic); "
                              "THRESHOLD calibrated on the real E2 corpus (embedder-specific). "
                              "Validated on E2: FPR/FNR/veto below. Fixes the a=0 N-R-axis "
                              "degeneracy found in audit 2026-07-06."),
              "honest_finding": ("H(x) magnitudes separate benign vs grave (AUROC "
                                 + str(hroc["benign_vs_grave"]) + ") but NOT camouflaged adversarial (AUROC "
                                 + str(hroc["benign_vs_adversarial"]) + "). Adversarial veto needs the "
                                 "negation-aware verifiability cue (VER fuse).")}
    rep_path = ev / "frontier_calibration.json"
    rep_path.write_text(json.dumps(report, indent=1))
    for p in (cfg_path, rep_path):
        print(p.name, "SHA256:", hashlib.sha256(p.read_bytes()).hexdigest())
    print(json.dumps({"H_params": report["H_params"], "degeneracy_check": degeneracy,
                      "metrics_v7_calibrated_H_plus_VERfuse": cal_hv}, indent=1))


if __name__ == "__main__":
    main()
